/**
 * ExchangeBot_DB
 * API for database service. mysql-to-rest is used as a manager (what api is)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ExchangeBotDb) {
      root.ExchangeBotDb = {};
    }
    root.ExchangeBotDb.IssuersApi = factory(root.ExchangeBotDb.ApiClient, root.ExchangeBotDb.GetResponse);
  }
}(this, function(ApiClient, GetResponse) {
  'use strict';

  /**
   * Issuers service.
   * @module api/IssuersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new IssuersApi. 
   * @alias module:api/IssuersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getIssuers operation.
     * @callback module:api/IssuersApi~getIssuersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * lists issuers
     * lists issuers added before
     * @param {module:api/IssuersApi~getIssuersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetResponse}
     */
    this.getIssuers = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetResponse;

      return this.apiClient.callApi(
        '/issuers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
