/**
 * ExchangeBot_DB
 * API for database service. mysql-to-rest is used as a manager (what api is)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ExchangeBotDb) {
      root.ExchangeBotDb = {};
    }
    root.ExchangeBotDb.GetResponse = factory(root.ExchangeBotDb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetResponse model module.
   * @module model/GetResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetResponse</code>.
   * @alias module:model/GetResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>GetResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetResponse} obj Optional instance to populate.
   * @return {module:model/GetResponse} The populated <code>GetResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('result')) {
        obj['result'] = ApiClient.convertToType(data['result'], 'String');
      }
      if (data.hasOwnProperty('json')) {
        obj['json'] = ApiClient.convertToType(data['json'], Object);
      }
      if (data.hasOwnProperty('table')) {
        obj['table'] = ApiClient.convertToType(data['table'], 'String');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} result
   */
  exports.prototype['result'] = undefined;
  /**
   * @member {Object} json
   */
  exports.prototype['json'] = undefined;
  /**
   * @member {String} table
   */
  exports.prototype['table'] = undefined;
  /**
   * @member {Number} length
   */
  exports.prototype['length'] = undefined;



  return exports;
}));


