/**
 * ExchangeBot_DB
 * API for database service. mysql-to-rest is used as a manager (what api is)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ExchangeBotDb) {
      root.ExchangeBotDb = {};
    }
    root.ExchangeBotDb.Issuers = factory(root.ExchangeBotDb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Issuers model module.
   * @module model/Issuers
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Issuers</code>.
   * @alias module:model/Issuers
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Issuers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Issuers} obj Optional instance to populate.
   * @return {module:model/Issuers} The populated <code>Issuers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('short_name')) {
        obj['short_name'] = ApiClient.convertToType(data['short_name'], 'String');
      }
      if (data.hasOwnProperty('full_name')) {
        obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
      }
      if (data.hasOwnProperty('url_stock')) {
        obj['url_stock'] = ApiClient.convertToType(data['url_stock'], 'String');
      }
      if (data.hasOwnProperty('url_price_history')) {
        obj['url_price_history'] = ApiClient.convertToType(data['url_price_history'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} short_name
   */
  exports.prototype['short_name'] = undefined;
  /**
   * @member {String} full_name
   */
  exports.prototype['full_name'] = undefined;
  /**
   * @member {String} url_stock
   */
  exports.prototype['url_stock'] = undefined;
  /**
   * @member {String} url_price_history
   */
  exports.prototype['url_price_history'] = undefined;



  return exports;
}));


