-- MySQL Script generated by MySQL Workbench
-- Sat Feb 25 15:32:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exchange_bot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exchange_bot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exchange_bot` DEFAULT CHARACTER SET utf8 ;
USE `exchange_bot` ;

-- -----------------------------------------------------
-- Table `exchange_bot`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `block_status` INT NOT NULL DEFAULT 0,
  `telegram_acc` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `country_id` INT NULL,
  `town_id` INT NULL,
  `sex` INT NULL,
  `birth_date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`frequency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`frequency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `good_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfrequency_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`users_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`users_tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  `source_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `frequency_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `frequency_id`),
  UNIQUE INDEX `idtasks_UNIQUE` (`id` ASC),
  INDEX `fk_users_tasks_users_idx` (`users_id` ASC),
  INDEX `fk_users_tasks_frequency1_idx` (`frequency_id` ASC),
  CONSTRAINT `fk_users_tasks_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `exchange_bot`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_tasks_frequency`
    FOREIGN KEY (`frequency_id`)
    REFERENCES `exchange_bot`.`frequency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(100) NULL,
  `method_name` VARCHAR(100) NULL,
  `value` VARCHAR(255) NULL,
  `datetime` DATETIME(6) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `idlog_UNIQUE` (`id` ASC),
  INDEX `fk_log_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_log_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `exchange_bot`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`source_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`source_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`sources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(500) NULL,
  `spider_name` VARCHAR(100) NULL,
  `source_types_id` INT NOT NULL,
  PRIMARY KEY (`id`, `source_types_id`),
  UNIQUE INDEX `idsources_UNIQUE` (`id` ASC),
  INDEX `fk_sources_source_types1_idx` (`source_types_id` ASC),
  CONSTRAINT `fk_sources_source_types1`
    FOREIGN KEY (`source_types_id`)
    REFERENCES `exchange_bot`.`source_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`content_collected`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`content_collected` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME(6) NOT NULL,
  `header` VARCHAR(255) NULL,
  `text` TEXT NULL,
  `url` VARCHAR(500) NULL,
  `md5` VARCHAR(32) NULL,
  `sources_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sources_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_idx` (`sources_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`sources_id`)
    REFERENCES `exchange_bot`.`sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`help`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`help` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `command_name` VARCHAR(45) NOT NULL,
  `help_string` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `command_name_UNIQUE` (`command_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exchange_bot`.`ads_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exchange_bot`.`ads_tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATETIME(6) NOT NULL,
  `date_end` DATETIME(6) NOT NULL,
  `content_id` INT NOT NULL,
  `good_time` TIME NULL,
  `frequency_id` INT NOT NULL,
  PRIMARY KEY (`id`, `frequency_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ads_tasks_frequency1_idx` (`frequency_id` ASC),
  CONSTRAINT `fk_ads_tasks_frequency`
    FOREIGN KEY (`frequency_id`)
    REFERENCES `exchange_bot`.`frequency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'parser' IDENTIFIED BY 'shaDOW';

GRANT SELECT, INSERT, TRIGGER ON TABLE `exchange_bot`.* TO 'parser';
CREATE USER 'manager' IDENTIFIED BY 'shaDOW';

GRANT SELECT, INSERT, TRIGGER ON TABLE `exchange_bot`.* TO 'manager';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `exchange_bot`.* TO 'manager';
GRANT EXECUTE ON ROUTINE `exchange_bot`.* TO 'manager';
CREATE USER 'publicator' IDENTIFIED BY 'shaDOW';

GRANT SELECT ON TABLE `exchange_bot`.* TO 'publicator';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
